# Generated by Django 4.0.2 on 2022-02-11 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('u_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('u_pw', models.CharField(max_length=100)),
                ('u_name', models.CharField(max_length=100)),
                ('u_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 11, 15, 29, 57, 603771))),
                ('u_hobby', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
