# Generated by Django 4.0.2 on 2022-02-10 01:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('board', '0002_alter_board_b_datd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='b_id',
        ),
        migrations.AddField(
            model_name='board',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='member.member'),
        ),
        migrations.AlterField(
            model_name='board',
            name='b_datd',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 10, 10, 3, 52, 171528)),
        ),
    ]
