# Generated by Django 4.0.2 on 2022-02-18 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_fboard_b_date_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='c_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 18, 15, 17, 58, 842767)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_pw',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fboard',
            name='b_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 18, 15, 17, 58, 842767)),
        ),
    ]
