# Generated by Django 4.0.2 on 2022-02-10 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_fboard_b_id_fboard_member_alter_fboard_b_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fboard',
            name='b_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fboard',
            name='b_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 10, 11, 9, 9, 345837)),
        ),
    ]
