# Generated by Django 4.0.2 on 2022-02-18 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_comment_c_date_alter_comment_c_pw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='c_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 18, 15, 27, 4, 344288), null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_pw',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='fboard',
            name='b_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 18, 15, 27, 4, 344288)),
        ),
    ]
