# Generated by Django 4.0.2 on 2022-02-10 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_board_b_id_board_member_alter_board_b_datd'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='b_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='board',
            name='b_datd',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 10, 11, 8, 37, 926659)),
        ),
    ]
