# Generated by Django 4.0.2 on 2022-02-18 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_rename_fboard_comment_board_alter_board_b_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 18, 15, 16, 16, 540456)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 18, 15, 16, 16, 540456)),
        ),
    ]
