# Generated by Django 4.0.2 on 2022-02-18 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_board_b_date_alter_comment_c_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 18, 15, 18, 9, 497363)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 18, 15, 18, 9, 497363)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_pw',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
