# Generated by Django 4.0.2 on 2022-03-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=0, max_length=100)),
                ('location', models.CharField(max_length=30)),
                ('deathcnt', models.IntegerField(default=0)),
                ('incdec', models.IntegerField(default=0)),
                ('defCnt', models.IntegerField(default=0)),
            ],
        ),
    ]
