# Generated by Django 4.0.2 on 2022-03-04 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fboard',
            fields=[
                ('b_no', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('b_title', models.CharField(max_length=1000)),
                ('b_content', models.TextField()),
                ('b_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 4, 15, 34, 37, 269334))),
                ('b_hit', models.IntegerField(default=1)),
            ],
        ),
    ]
