# Generated by Django 4.0.2 on 2022-03-06 05:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_fboard_b_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fboard',
            name='b_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 6, 14, 58, 30, 287673)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('c_no', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('c_pw', models.CharField(blank=True, max_length=10)),
                ('c_content', models.TextField()),
                ('c_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 6, 14, 58, 30, 287673), null=True)),
                ('c_spw', models.IntegerField(default='1234')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.fboard')),
            ],
        ),
    ]
