# Generated by Django 4.0.2 on 2022-02-08 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeboard',
            name='b_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 8, 14, 58, 51, 695264)),
        ),
    ]
