# Generated by Django 4.0.2 on 2022-03-04 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_comment_c_date_alter_news_n_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='c_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 5, 0, 12, 32, 981163), null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 5, 0, 12, 32, 981163)),
        ),
    ]
