# Generated by Django 4.0.2 on 2022-02-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('m_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('m_pw', models.CharField(max_length=100)),
                ('m_name', models.CharField(max_length=100)),
            ],
        ),
    ]
